version: '3.6'
services:
  service:
    image: custom-image-processing:latest
    build:
      context: .
      target: service
      platforms:
        - linux/arm64
    platform: linux/arm64
    user: "1000:1000"
    ports:
      - "8099:8099"
    command: uvicorn openapi_server.main:app --host 0.0.0.0 --port 8099
    volumes:
      - /tmp/custom_image_processing/raw:/tmp/custom_image_processing/raw:ro
      - /tmp/custom_image_processing/processed:/tmp/custom_image_processing/processed:rw
